<a href="https://colab.research.google.com/github/tomtmot/20220702_python/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data=np.arange(25)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [3]:
type(data)

numpy.ndarray

In [4]:
data[3:4]

array([3])

In [5]:
type(data[3])

numpy.int64

In [6]:
type(data)

numpy.ndarray

In [7]:
data.shape

(25,)

In [8]:
data1=data.reshape(1,25)
data1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [9]:
type(data1)

numpy.ndarray

In [10]:
len(data1)

1

In [11]:
data1.size

25

In [12]:
data1.shape

(1, 25)

In [13]:
data1[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
data2=data.reshape(25,1)
data2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [15]:
len(data2)

25

In [16]:
data2.size

25

In [17]:
data2[5]

array([5])

In [18]:
data2[5][0]

5

In [19]:
data3=data.reshape(5,5)
data3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
data3.size

25

In [21]:
data3[3]

array([15, 16, 17, 18, 19])

In [22]:
data3[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
d

NameError: ignored

In [ ]:
data3

In [ ]:
data3[1][1:3]

In [ ]:
x=[1,2,3,4]

In [ ]:
plt.plot(x)